-- =============================================================================
-- V3 - Authentication, RBAC and Audit foundation (HRMS Payroll MVP, task V0-003)
--
-- Implements the identity/security schema required by the API & Backend
-- Requirements Specification (sections 5-6) and the AuditLog entity from the
-- Data Model specification (section 15).
--
-- Tables (dependency order):
--   1. app_user          (login identity + password hash + scope + MFA state)
--   2. role              (SUPER_ADMIN / COMPANY_ADMIN / PAYROLL_ADMIN + reserved)
--   3. permission        (explicit permission codes)
--   4. role_permission   (role -> permission mapping)
--   5. user_role         (user -> role assignment)
--   6. revoked_token     (JWT denylist for logout / password-change revocation)
--   7. audit_log         (Data Model 15.1 - append-only material-action history)
--
-- Also finalises the deferred foreign keys documented in V2: the placeholder
-- created_by columns in statutory_configuration and work_calendar_assignment
-- now reference app_user (the users/actor table introduced here).
--
-- Conventions follow V2: UUID PKs generated by the application; enum domains as
-- VARCHAR + CHECK (portable across PostgreSQL and the H2 test database);
-- pk_/fk_/ck_/ix_/uq_ named constraints; TIMESTAMP for audit times.
--
-- Security note: this schema stores password HASHES only (never plaintext) and
-- the audit_log deliberately has NO column for secrets/hashes/tokens.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. app_user
--    "app_user" avoids the reserved word "user". Company-scoped users carry a
--    company_id; platform-scoped users (SUPER_ADMIN) have company_id NULL.
--    token_version is incremented on password change to invalidate prior JWTs.
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id             UUID         NOT NULL,
    username       VARCHAR(150) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    scope_type     VARCHAR(20)  NOT NULL,
    company_id     UUID         NULL,
    mfa_enabled    BOOLEAN      NOT NULL DEFAULT FALSE,
    mfa_secret     VARCHAR(100) NULL,
    token_version  INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT fk_app_user_company
        FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_app_user_scope_type CHECK (scope_type IN ('PLATFORM', 'COMPANY')),
    -- Platform users must not be bound to a company; company users must be.
    CONSTRAINT ck_app_user_scope_company CHECK (
        (scope_type = 'PLATFORM' AND company_id IS NULL)
        OR (scope_type = 'COMPANY' AND company_id IS NOT NULL))
);

CREATE INDEX ix_app_user_company_id ON app_user (company_id);

-- ---------------------------------------------------------------------------
-- 2. role
--    "assignable" is FALSE for roles reserved for future modules (EMPLOYEE for
--    ESS, MANAGER for MSS) so v0 cannot assign them.
-- ---------------------------------------------------------------------------
CREATE TABLE role (
    id          UUID         NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    scope_type  VARCHAR(20)  NOT NULL,
    assignable  BOOLEAN      NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT uq_role_code UNIQUE (code),
    CONSTRAINT ck_role_scope_type CHECK (scope_type IN ('PLATFORM', 'COMPANY'))
);

-- ---------------------------------------------------------------------------
-- 3. permission
-- ---------------------------------------------------------------------------
CREATE TABLE permission (
    id           UUID         NOT NULL,
    code         VARCHAR(100) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_permission PRIMARY KEY (id),
    CONSTRAINT uq_permission_code UNIQUE (code)
);

-- ---------------------------------------------------------------------------
-- 4. role_permission  (role -> permission mapping)
-- ---------------------------------------------------------------------------
CREATE TABLE role_permission (
    id             UUID      NOT NULL,
    role_id        UUID      NOT NULL,
    permission_id  UUID      NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (id),
    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id) REFERENCES permission (id),
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE INDEX ix_role_permission_role_id ON role_permission (role_id);
CREATE INDEX ix_role_permission_permission_id ON role_permission (permission_id);

-- ---------------------------------------------------------------------------
-- 5. user_role  (user -> role assignment)
-- ---------------------------------------------------------------------------
CREATE TABLE user_role (
    id       UUID NOT NULL,
    user_id  UUID NOT NULL,
    role_id  UUID NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX ix_user_role_user_id ON user_role (user_id);
CREATE INDEX ix_user_role_role_id ON user_role (role_id);

-- ---------------------------------------------------------------------------
-- 6. revoked_token
--    JWT denylist keyed by token id (jti). Used by logout and can be used to
--    revoke tokens on password change. expires_at allows periodic cleanup.
-- ---------------------------------------------------------------------------
CREATE TABLE revoked_token (
    jti         VARCHAR(64) NOT NULL,
    user_id     UUID        NOT NULL,
    expires_at  TIMESTAMP   NOT NULL,
    revoked_at  TIMESTAMP   NOT NULL,
    CONSTRAINT pk_revoked_token PRIMARY KEY (jti),
    CONSTRAINT fk_revoked_token_user
        FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_revoked_token_user_id ON revoked_token (user_id);
CREATE INDEX ix_revoked_token_expires_at ON revoked_token (expires_at);

-- ---------------------------------------------------------------------------
-- 7. audit_log  (Data Model 15.1)
--    Append-only. actor_user_id references app_user. company_id references
--    company. Snapshots/reason are free text/JSON; NO secret material is stored.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id               UUID         NOT NULL,
    company_id       UUID         NULL,
    legal_entity_id  UUID         NULL,
    actor_user_id    UUID         NOT NULL,
    action           VARCHAR(100) NOT NULL,
    entity_type      VARCHAR(100) NOT NULL,
    entity_id        UUID         NULL,
    scope_type       VARCHAR(20)  NOT NULL,
    outcome          VARCHAR(20)  NULL,
    occurred_at      TIMESTAMP    NOT NULL,
    before_snapshot  TEXT         NULL,
    after_snapshot   TEXT         NULL,
    reason           TEXT         NULL,
    request_id       VARCHAR(100) NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_audit_log_actor
        FOREIGN KEY (actor_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_audit_log_company
        FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT ck_audit_log_scope_type
        CHECK (scope_type IN ('PLATFORM', 'COMPANY')),
    CONSTRAINT ck_audit_log_outcome
        CHECK (outcome IS NULL OR outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX ix_audit_log_actor_user_id ON audit_log (actor_user_id);
CREATE INDEX ix_audit_log_company_id ON audit_log (company_id);
CREATE INDEX ix_audit_log_occurred_at ON audit_log (occurred_at);
CREATE INDEX ix_audit_log_action ON audit_log (action);

-- ---------------------------------------------------------------------------
-- 8. Finalise deferred V2 foreign keys now that app_user exists.
--    These columns were created in V2 as typed placeholders awaiting the
--    users/actor table (see V2 header notes). The tables are empty, so adding
--    the constraints here is safe and does not modify the V2 migration.
-- ---------------------------------------------------------------------------
ALTER TABLE statutory_configuration
    ADD CONSTRAINT fk_statutory_config_created_by
        FOREIGN KEY (created_by) REFERENCES app_user (id);

ALTER TABLE work_calendar_assignment
    ADD CONSTRAINT fk_wca_created_by
        FOREIGN KEY (created_by) REFERENCES app_user (id);
